### PR TITLE
Creating initial empty files

### PR DESCRIPTION
**Pull request by AlexMikes**
This is my first pull request!

### CODE REVIEW

**Review by sylvan-sh — APPROVED** [review]
Looks good! I'm not sure the role of the first line comment about the environment. I recall that being something spyder does w/ every new file.

**Comment by kyleniemeyer** [comment]
That bit at the top is called a "shebang", and is only necessary if you are going to run a file directly as an executable.

**Comment by sylvan-sh** [comment]
@kyleniemeyer If we leave them, do they need to be modified as suggested [here](https://stackoverflow.com/a/19305076/9507437)?

**Comment by kyleniemeyer** [comment]
Probably, yes. though in general I would remove them from most of the files, unless one is the "main" file

**Pull request merged**
